### ISSUE TITLE
[Symfony] Documentation error

### ISSUE THREAD

**Issue by LauLaman** [web-auth/webauthn-framework#198]
**Describe the bug**
on the [Symfony firewall documentation](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way/firewall) a `UserProvider` is described. on line 29 of the `src/Repository/UserRepository.php`, doctrines generic `find()` is being used to loopup the user. This will never work as doctrine will try to retrieve using the objects identifier (primary key) and we want to load the user by its username.

Since we're already using the `UserRepository` which is described on page [Entities with Doctrine](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way/entities-with-doctrine#the-repository-1) we can use the already implemented method `findOneByUsername()` Which is derived from `AbstractPublicKeyCredentialUserEntityRepository`

1. Folow documentation for "The Symfony Way" 

**Expected behavior**

**Screenshots**
![Screenshot 2021-11-26 at 01 44 31](https://user-images.githubusercontent.com/8283992/143511265-c9e6fc84-9fd7-4d95-8a48-1e11c9438f5d.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by LauLaman** [comment]
one other small remark: `UsernameNotFoundException` has been deprecated in favor of `UserNotFoundException` (since Symfony 5.3)

**Comment by Spomky** [comment]
Hi,

Thank you for posting this issue.
Actually, there is no mistake here from my point of view.

The bundle can be install on Symfony 4.4 and 5.x therefore the `UserNotFoundException` and `findOneByIdentifier` introduced in recently release Symfony version cannot be used in other ones. With that being said, you are right to say that new features should be used instead of deprecated ones.

Regarding your comment about the repository, you are right. The repository shall implement the interface [`PublicKeyCredentialUserEntityRepository`](https://github.com/web-auth/webauthn-framework/blob/v3.3.10/src/symfony/src/Repository/PublicKeyCredentialUserEntityRepository.php) and `findOneByUsername` should be called.
The documentation will be updated accordingly.
Please not that this is not directly linked to Doctrine, but the naming of the methods from the interface.

**Comment by LauLaman** [comment]
@Spomky you're right about the deprecations. however with Symfony 6 around the corner maybe update the example to the latest and add a note for < Symfony 5.3

i could not find the repository for the documentation otherwise i would have created a pR
