### ISSUE TITLE
Create possibility to set transports to internal

### ISSUE THREAD

**Issue by Tsjippy** [web-auth/webauthn-framework#202]
**Is your feature request related to a problem? Please describe.**
As far as I know you cannot set the transport modes easily. This is very annoying for me as I want to set it to internal, to prevent asking for external keys.

**Describe the solution you'd like**
It would be great if we could set transportmode to internal manually or automatically if AuthenticatorSelectionCriteria is set to AUTHENTICATOR_ATTACHMENT_PLATFORM.

**Describe alternatives you've considered**
Right now I fixed it in a very ugly way by recreating the publicKeyCredentialSource during storage like this:
```
$publicKeyCredentialSource = new PublicKeyCredentialSource(
                $publicKeyCredentialSource->getPublicKeyCredentialId(),
                'public-key',
                ['internal'],
                $publicKeyCredentialSource->getAttestationType(),
                $publicKeyCredentialSource->getTrustPath(),
                $publicKeyCredentialSource->getAaguid(),
                $publicKeyCredentialSource->getCredentialPublicKey(),
                $publicKeyCredentialSource->getUserHandle(),
                $publicKeyCredentialSource->getCounter(),
                $publicKeyCredentialSource->getOtherUI()
            );
```

**Additional context**

**Comment by Spomky** [comment]
Hi,

Since Webauthn 2, there is a [`getTransports()`](https://www.w3.org/TR/webauthn-2/#dom-authenticatorattestationresponse-gettransports) method that allows us to know the allowed modes between the client and the authenticator.
This version of the specification is not completely implemented here, but this is definitely something that will be.

This new method will help solving that issue.
