### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by ThibaudDauce** [web-auth/webauthn-framework#206]
Laravel 9 switched to Symfony 6 components and this library is not compatible with Symfony 6.

Is Symfony 6 support possible? Or is it hard and will to be before some time?

Thanks for the great package!

PS: I'm using only the https://github.com/web-auth/webauthn-lib package to provide WebAuthN feature to my login page.

**Comment by Spomky** [comment]
Hi @ThibaudDauce,

We need to update some dependencies first (in particular the web-token stuff).
This suite is the next one on the list.

**Comment by ThibaudDauce** [comment]
Thanks for your response, do you have a estimated deadline for the v4? If you want, my company can sponsor this update (depending on the cost :-) )

**Comment by Spomky** [comment]
Hi @ThibaudDauce,

I don't have an ETA at the moment. I have just completed the implementation of the Symfony 6 authentication system.
The next step is to adhere to the Metadata Statement (MDS) v3 specification, as this is now the official standard. Without this, the framework will not pass Fido Alliance testing.
I think it should be done by the end of March (I'll do my best to have it by then).
Note that this major release breaks a lot of stuff, especially if you're dealing with MDS.

I tried to allow SF6 components in the v3.x branch, but since SF6 uses type hints heavily, it's a pain...

**Comment by prolonginc** [comment]
Hello @Spomky  i was wondering if this is still in progress and if there was an ETA on it. I really appreciate your hard work on this and was just wondering if this going to be released i could wait on one of my projects on it. 

thanks again.

**Comment by Spomky** [comment]
Hi @prolonginc,

It is ready. I am tuning the last details to make sure it fulfill with the Fido Alliance Test Tool.
I think it will be released today.

**Comment by prolonginc** [comment]
You are the best @Spomky  :) thank you thank you

**Comment by tydoo** [comment]
Thanks you @Spomky  :)

**Comment by Spomky** [comment]
Hi,

Version 4.0.0 is now available.
The documentation is also up to date. Please refer to the [migration path](https://webauthn-doc.spomky-labs.com/migration/from-v3.x-to-v4.0) (especially if you are using the MDS or Symfony Flex).

Let me know if you have any problems or if I missed explaining some changes in the documentation.
