### ISSUE TITLE
Unable to load stimulus controller

### ISSUE THREAD

**Issue by nicodemuz** [web-auth/webauthn-framework#466]
### Version(s) affected

4.7.0

### Description

I'm using webauthn framework with Stimulus and Symfony.

I'm using version 4.5.2 on project A.
I'm using version 4.7.0 on project B.

Project A works fine and I can see in the browser developer console the messages:
```
web-auth--webauthn-stimulus--webauthn #initialize
web-auth--webauthn-stimulus--webauthn #connect
```

I just setup project B using similar approach as project A, but unable to get the stimulus controller to initialize.

After downgrading project B from 4.7.0 to 4.5.2 it seems to initialize. Are there some upgrade steps to 4.7.0 that I am missing or that are undocumented?

### How to reproduce

Install version 4.7.0.

**Comment by Spomky** [comment]
Hi,

Many thanks for reporting this issue.
I investigated and this is not due to the changes from `4.7.x`, but `4.6.x`. I do not know exactly the reason, but the component is provided under the namespace `@web-auth/webauthn-stimulus` instead of `@web-auth/webauthn-stimulus/webauthn`.
If you try to change all occurrences in your templates, it should work as expected.
I will trye to fix that (I don't know how TBH).

**Comment by Spomky** [comment]
I am unable to have the previous behavior.
This issue will be pinned to help similar cases.
